import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import produce from "immer";
import { getResetPasswordInstructions } from "./passwordAPI";

export const Statuses = {
  Initial: "Not Fetched",
  Loading: "Loading..",
  UpToDate: "Up To Date",
  Deleted: "Deleted",
  Error: "Error",
};

const initialState = {
  status: Statuses.Initial,
};

export const getResetPasswordInstructionsAsync = createAsyncThunk(
  "users/password",
  async (payload) => {
    const response = await getResetPasswordInstructions(payload);
    return response;
  }
);

export const passwordSlice = createSlice({
  name: "password",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      // while you wait
      .addCase(getResetPasswordInstructionsAsync.pending, (state) => {
        return produce(state, (draftState) => {
          draftState.status = Statuses.Loading;
        });
      })
      // you got the thing
      .addCase(getResetPasswordInstructionsAsync.fulfilled, (state, action) => {
        return produce(state, (draftState) => {
          draftState.status = Statuses.UpToDate;
        });
      })
      // error
      .addCase(getResetPasswordInstructionsAsync.rejected, (state) => {
        return produce(state, (draftState) => {
          draftState.status = Statuses.Error;
        });
      });
  },
});

export const {} = passwordSlice.actions;

export default passwordSlice.reducer;
